server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    # reWriteBatchedInserts=true 批量插入时有性能提升
    url: jdbc:postgresql://localhost:5432/permission_management?reWriteBatchedInserts=true
    username: postgres
    password: 12345
mybatis:
  #mapper.xml的位置
  mapper-locations: classpath:./mapper/*Mapper.xml
  #定义实体类的别名
  type-aliases-package: io.github.homxuwang.entity
  # 把数据库的下划线字段映射成不带下划线的
  configuration:
    map-underscore-to-camel-case: true
#logging:
  # 打印mybatis的查询SQL
#  level.io.github.homxuwang.dao: debug